Repository prgrms-web-devcourse/Team_Price_Offer_BE, pull requests merged in 2021-12, with the labels that each got.

#14 Feat/#11
  build.gradle
  src/main/java/com/prgrms/offer/common/message/DtoValidationMessage.java
  src/main/java/com/prgrms/offer/common/message/ResponseMessage.java
  src/main/java/com/prgrms/offer/common/utils/S3ImageUploader.java
  src/main/java/com/prgrms/offer/core/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleBriefViewResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleCreateRequest.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleCreateResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/entity/Article.java
  src/main/java/com/prgrms/offer/domain/article/model/entity/ProductImage.java
  src/main/java/com/prgrms/offer/domain/article/model/value/TradeStatus.java
  src/main/java/com/prgrms/offer/domain/article/repository/ArticleRepository.java
  src/main/java/com/prgrms/offer/domain/article/repository/ProductImageRepository.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleConverter.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
  src/main/resources/sql/schema.sql
Labels: 리뷰 요청, feature

#23 Feat/#17
  .gitignore
  src/main/java/com/prgrms/offer/common/message/DtoValidationMessage.java
  src/main/java/com/prgrms/offer/common/message/ResponseMessage.java
  src/main/java/com/prgrms/offer/core/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleBriefViewResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleCreateOrUpdateRequest.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleCreateOrUpdateResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleDetailResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/entity/Article.java
  src/main/java/com/prgrms/offer/domain/article/model/entity/LikeArticle.java
  src/main/java/com/prgrms/offer/domain/article/repository/LikeArticleRepository.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleConverter.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
  src/main/java/com/prgrms/offer/domain/article/service/LikeArticleService.java
  src/main/resources/sql/schema.sql
Labels: feature

#29 Feat/#24
  src/main/java/com/prgrms/offer/common/message/ResponseMessage.java
  src/main/java/com/prgrms/offer/core/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/article/controller/LikeArticleController.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/LikeArticleStatusResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/entity/Article.java
  src/main/java/com/prgrms/offer/domain/article/model/entity/LikeArticle.java
  src/main/java/com/prgrms/offer/domain/article/repository/ArticleRepository.java
  src/main/java/com/prgrms/offer/domain/article/repository/LikeArticleRepository.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
  src/main/java/com/prgrms/offer/domain/article/service/LikeArticleConverter.java
  src/main/java/com/prgrms/offer/domain/article/service/LikeArticleService.java
  src/main/resources/sql/schema.sql
Labels: 리뷰 요청, feature

#31 Feat/#30
  src/main/java/com/prgrms/offer/common/page/PageDto.java
  src/main/java/com/prgrms/offer/common/page/PageInfo.java
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/member/model/entity/Member.java
  src/main/resources/sql/data.sql
  src/main/resources/sql/schema.sql
Labels: feature

#33 Feat/#32
  src/main/java/com/prgrms/offer/common/page/PageDto.java
  src/main/java/com/prgrms/offer/common/page/PageInfo.java
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleBriefViewResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleCreateOrUpdateResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleDetailResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/CategoriesResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/CodeAndName.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/CodeAndNameInfosResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/LikeArticleStatusResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/value/ProductStatus.java
  src/main/java/com/prgrms/offer/domain/article/model/value/TradeMethod.java
  src/main/java/com/prgrms/offer/domain/article/model/value/TradeStatus.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleConverter.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
Labels: feature

#37 Feat/#34
  src/main/java/com/prgrms/offer/common/message/DtoValidationMessage.java
  src/main/java/com/prgrms/offer/common/message/ResponseMessage.java
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleDetailResponse.java
  src/main/java/com/prgrms/offer/domain/offer/controller/OfferController.java
  src/main/java/com/prgrms/offer/domain/offer/model/dto/OfferCreateRequest.java
  src/main/java/com/prgrms/offer/domain/offer/model/dto/OfferResponse.java
  src/main/java/com/prgrms/offer/domain/offer/model/entity/Offer.java
  src/main/java/com/prgrms/offer/domain/offer/repository/OfferRepository.java
  src/main/java/com/prgrms/offer/domain/offer/service/OfferConverter.java
  src/main/java/com/prgrms/offer/domain/offer/service/OfferService.java
  src/main/resources/sql/schema.sql
Labels: feature

#39 Feat/#38
  src/main/java/com/prgrms/offer/common/message/ResponseMessage.java
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/article/model/entity/Article.java
  src/main/java/com/prgrms/offer/domain/article/repository/ArticleRepository.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
  src/main/java/com/prgrms/offer/domain/offer/controller/OfferController.java
  src/main/resources/sql/schema.sql
Labels: feature

#43 Feat/#40
  .gitignore
  src/main/java/com/prgrms/offer/common/message/DtoValidationMessage.java
  src/main/java/com/prgrms/offer/common/message/ResponseMessage.java
  src/main/java/com/prgrms/offer/common/utils/S3ImageUploader.java
  src/main/java/com/prgrms/offer/core/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/article/model/entity/Article.java
  src/main/java/com/prgrms/offer/domain/article/model/value/TradeStatus.java
  src/main/java/com/prgrms/offer/domain/article/repository/ArticleRepository.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
  src/main/java/com/prgrms/offer/domain/review/controller/ReviewController.java
  src/main/java/com/prgrms/offer/domain/review/model/dto/ReviewCreateRequest.java
  src/main/java/com/prgrms/offer/domain/review/model/dto/ReviewCreateResponse.java
  src/main/java/com/prgrms/offer/domain/review/model/entity/Review.java
  src/main/java/com/prgrms/offer/domain/review/repository/ReviewRepository.java
  src/main/java/com/prgrms/offer/domain/review/service/ReviewConverter.java
  src/main/java/com/prgrms/offer/domain/review/service/ReviewService.java
  src/main/resources/sql/schema.sql
Labels: feature

#44 [사용자] 좋아요한 게시글 조회
  src/main/java/com/prgrms/offer/domain/article/controller/LikeArticleController.java
  src/main/java/com/prgrms/offer/domain/article/model/entity/LikeArticle.java
  src/main/java/com/prgrms/offer/domain/article/repository/LikeArticleRepository.java
  src/main/java/com/prgrms/offer/domain/article/service/LikeArticleService.java
  src/main/java/com/prgrms/offer/domain/member/controller/MemberController.java
Labels: feature

#50 Feat/#45
  .gitignore
  src/main/java/com/prgrms/offer/common/message/ResponseMessage.java
  src/main/java/com/prgrms/offer/common/page/PageDto.java
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
  src/main/java/com/prgrms/offer/domain/offer/controller/OfferController.java
  src/main/java/com/prgrms/offer/domain/offer/model/dto/OfferResponse.java
  src/main/java/com/prgrms/offer/domain/offer/repository/OfferRepository.java
  src/main/java/com/prgrms/offer/domain/offer/service/OfferConverter.java
  src/main/java/com/prgrms/offer/domain/offer/service/OfferService.java
  src/main/java/com/prgrms/offer/domain/review/controller/ReviewController.java
  src/main/java/com/prgrms/offer/domain/review/model/dto/ReviewResponse.java
  src/main/java/com/prgrms/offer/domain/review/model/entity/Review.java
  src/main/java/com/prgrms/offer/domain/review/repository/ReviewRepository.java
  src/main/java/com/prgrms/offer/domain/review/service/ReviewConverter.java
  src/main/java/com/prgrms/offer/domain/review/service/ReviewService.java
Labels: feature

#61 Feat/#52
  src/main/java/com/prgrms/offer/common/message/ResponseMessage.java
  src/main/java/com/prgrms/offer/core/config/SwaggerConfig.java
  src/main/java/com/prgrms/offer/core/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleDetailResponse.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleConverter.java
  src/main/java/com/prgrms/offer/domain/member/model/entity/Member.java
  src/main/java/com/prgrms/offer/domain/member/model/value/Score.java
  src/main/java/com/prgrms/offer/domain/review/controller/ReviewController.java
  src/main/java/com/prgrms/offer/domain/review/model/dto/ReviewResponse.java
  src/main/java/com/prgrms/offer/domain/review/model/value/OfferLevel.java
  src/main/java/com/prgrms/offer/domain/review/service/ReviewConverter.java
  src/main/java/com/prgrms/offer/domain/review/service/ReviewService.java
Labels: feature

#67 Feat/#64
  src/main/java/com/prgrms/offer/common/message/ResponseMessage.java
  src/main/java/com/prgrms/offer/domain/offer/repository/OfferRepository.java
  src/main/java/com/prgrms/offer/domain/review/controller/ReviewController.java
  src/main/java/com/prgrms/offer/domain/review/service/ReviewService.java
Labels: feature

#70 Feat/#69
  src/main/java/com/prgrms/offer/domain/review/controller/ReviewController.java
  src/main/java/com/prgrms/offer/domain/review/service/ReviewService.java
Labels: feature

#75 Feat/#73
  src/main/java/com/prgrms/offer/common/message/ResponseMessage.java
  src/main/java/com/prgrms/offer/domain/review/controller/ReviewController.java
  src/main/java/com/prgrms/offer/domain/review/model/dto/ReviewResponse.java
  src/main/java/com/prgrms/offer/domain/review/repository/ReviewRepository.java
  src/main/java/com/prgrms/offer/domain/review/service/ReviewConverter.java
  src/main/java/com/prgrms/offer/domain/review/service/ReviewService.java
Labels: feature

#77 Feat/#76
  src/main/java/com/prgrms/offer/domain/review/controller/ReviewController.java
  src/main/java/com/prgrms/offer/domain/review/repository/ReviewRepository.java
Labels: feature

#79 Feat/#78
  src/main/java/com/prgrms/offer/OfferApplication.java
  src/main/java/com/prgrms/offer/domain/offer/model/dto/OfferResponse.java
  src/main/java/com/prgrms/offer/domain/offer/service/OfferConverter.java
Labels: feature

#81 Feat/#80
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleDetailResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleWithOfferBriefViewResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/CodeAndName.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleConverter.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
  src/main/java/com/prgrms/offer/domain/offer/model/dto/OfferBriefResponse.java
  src/main/java/com/prgrms/offer/domain/offer/model/dto/OfferResponse.java
  src/main/java/com/prgrms/offer/domain/offer/repository/OfferRepository.java
  src/main/java/com/prgrms/offer/domain/review/model/dto/ReviewResponse.java
Labels: feature

#99 Feat/#97, #96
  src/main/java/com/prgrms/offer/core/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/offer/domain/article/repository/ArticleRepository.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
  src/main/java/com/prgrms/offer/domain/offer/repository/OfferRepository.java
  src/main/java/com/prgrms/offer/domain/review/service/ReviewService.java
Labels: feature

#108 Feat/#100
  src/main/java/com/prgrms/offer/domain/article/model/entity/LikeArticle.java
  src/main/java/com/prgrms/offer/domain/article/model/entity/ProductImage.java
  src/main/java/com/prgrms/offer/domain/article/repository/LikeArticleRepository.java
  src/main/java/com/prgrms/offer/domain/article/repository/ProductImageRepository.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
  src/main/java/com/prgrms/offer/domain/message/repository/MessageRoomRepository.java
  src/main/java/com/prgrms/offer/domain/offer/repository/OfferRepository.java
  src/main/java/com/prgrms/offer/domain/review/repository/ReviewRepository.java
Labels: bugfix

#128 Feat/#122
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleConverter.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
  src/main/java/com/prgrms/offer/domain/offer/repository/OfferRepository.java
  src/main/java/com/prgrms/offer/domain/review/service/ReviewService.java
Labels: feature

#131 Feat/#130
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/article/repository/ArticleRepository.java
  src/main/java/com/prgrms/offer/domain/article/repository/LikeArticleRepository.java
  src/main/java/com/prgrms/offer/domain/article/repository/TemporalArticle.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleConverter.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
  src/main/java/com/prgrms/offer/domain/offer/repository/OfferRepository.java
Labels: bugfix
