Repository prgrms-web-devcourse/Team_Price_Offer_BE, pull requests merged in 2021-11, with the labels that each got.

#2 [인프라] 스프링 시큐리티 설정 및 기본 패키지 구조 구성
  src/main/java/com/prgrms/offer/common/ApiResponse.java
  src/main/java/com/prgrms/offer/core/config/WebSecurityConfig.java
  src/main/java/com/prgrms/offer/domain/member/model/entity/Member.java
Labels: 리뷰 요청, infra

#7 [인프라] JWT 기반 인증을 위한 스프링 시큐리티 설정
  build.gradle
  src/main/java/com/prgrms/offer/core/config/WebSecurityConfig.java
  src/main/java/com/prgrms/offer/core/jwt/Jwt.java
  src/main/java/com/prgrms/offer/core/jwt/JwtAuthentication.java
  src/main/java/com/prgrms/offer/core/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/offer/core/jwt/JwtAuthenticationProvider.java
  src/main/java/com/prgrms/offer/core/jwt/JwtAuthenticationToken.java
  src/main/java/com/prgrms/offer/core/jwt/JwtConfigure.java
  src/main/java/com/prgrms/offer/domain/member/model/entity/LoginRequest.java
  src/main/java/com/prgrms/offer/domain/member/model/entity/LoginResponse.java
  src/main/java/com/prgrms/offer/domain/member/model/entity/Member.java
  src/main/java/com/prgrms/offer/domain/member/model/entity/MemberController.java
  src/main/java/com/prgrms/offer/domain/member/model/entity/MemberRepository.java
  src/main/java/com/prgrms/offer/domain/member/model/entity/MemberService.java
  src/main/resources/sql/data.sql
  src/main/resources/sql/schema.sql
Labels: infra

#6 Feat/#5 article 일부 및 예외처리 로직 구현
  build.gradle
  src/main/java/com/prgrms/offer/common/ApiResponse.java
  src/main/java/com/prgrms/offer/common/message/ResponseMessage.java
  src/main/java/com/prgrms/offer/core/config/SwaggerConfig.java
  src/main/java/com/prgrms/offer/core/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/offer/core/error/exception/BusinessException.java
  src/main/java/com/prgrms/offer/domain/article/controller/ArticleController.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/ArticleBriefViewResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/dto/CategoriesResponse.java
  src/main/java/com/prgrms/offer/domain/article/model/entity/Article.java
  src/main/java/com/prgrms/offer/domain/article/model/value/Category.java
  src/main/java/com/prgrms/offer/domain/article/model/value/ProductStatus.java
  src/main/java/com/prgrms/offer/domain/article/model/value/TradeMethod.java
  src/main/java/com/prgrms/offer/domain/article/model/value/TradeStatus.java
  src/main/java/com/prgrms/offer/domain/article/repository/ArticleRepository.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleConverter.java
  src/main/java/com/prgrms/offer/domain/article/service/ArticleService.java
Labels: 리뷰 요청, feature
